package io.quarkiverse.amazon.dynamodb.enhanced.deployment;

import java.util.Arrays;
import java.util.List;

import org.jboss.jandex.DotName;

import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AtomicCounterExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedUuidExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension;

final class DynamoDbEnhancedClientExtensionsDotNames {

    static final DotName DYNAMODB_ENHANCED_CLIENT_EXTENSION_NAME = DotName
            .createSimple(DynamoDbEnhancedClientExtension.class.getName());

    // well-known client extensions
    static final DotName ATOMIC_COUNTER_EXTENSION_NAME = DotName
            .createSimple(AtomicCounterExtension.class.getName());
    static final DotName AUTO_GENERATED_TIMESTAMP_RECORD_EXTENSION_NAME = DotName
            .createSimple(AutoGeneratedTimestampRecordExtension.class.getName());
    static final DotName AUTO_GENERATED_UUID_EXTENSION_NAME = DotName
            .createSimple(AutoGeneratedUuidExtension.class.getName());
    static final DotName VERSIONED_RECORD_EXTENSION_NAME = DotName
            .createSimple(VersionedRecordExtension.class.getName());

    static final List<DotName> WELL_KNOWN_CLIENT_EXTENSIONS_LIST = Arrays.asList(
            ATOMIC_COUNTER_EXTENSION_NAME,
            AUTO_GENERATED_TIMESTAMP_RECORD_EXTENSION_NAME,
            AUTO_GENERATED_UUID_EXTENSION_NAME,
            VERSIONED_RECORD_EXTENSION_NAME);

    private DynamoDbEnhancedClientExtensionsDotNames() {
    }

}
