:service-name: appconfigdata
:service-name-uppercase: AppConfigData

= Amazon AppConfigData Client

include::./includes/attributes.adoc[]

Amazon AppConfigData is a service for managing application configurations.

You can find more information about AppConfigData at https://aws.amazon.com/systems-manager/features/#AppConfigData[the Amazon AppConfigData website].

NOTE: The AppConfigData extension is based on https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html[AWS Java SDK 2.x].
It's a major rewrite of the 1.x code base that offers two programming models (Blocking & Async).

The Quarkus extension supports two programming models:

* Blocking access using URL Connection HTTP client (by default) or the Apache HTTP Client
* https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html[Asynchronous programming] based on JDK's `CompletableFuture` objects and the Netty HTTP client (by default) or the AWS CRT-based HTTP client

You can use this extension to integrate AppConfigData capabilities in your Quarkus applications using the AWS SDK for Java 2.x.

include::./amazon-configure-clients.adoc[]

== Usage

You can inject the AppConfigData client in your Quarkus beans using:

[source,java]
----
import software.amazon.awssdk.services.appconfigdata.AppConfigDataClient;
import software.amazon.awssdk.services.appconfigdata.model.GetLatestConfigurationRequest;
import software.amazon.awssdk.services.appconfigdata.model.GetLatestConfigurationResponse;

import jakarta.inject.Inject;
import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class AppConfigDataService {

    @Inject
    AppConfigDataClient appConfigDataClient;

    public void listApplications() {
        GetLatestConfigurationResponse response = client.getLatestConfiguration(GetLatestConfigurationRequest.builder().build());
        // Handle response, e.g. iterate over response.items()
    }
}
----

== Configuration Reference

include::./amazon-configure-clients.adoc[]

== Related Guides

For more information, check out:
- https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfigdata.html[AWS AppConfigData Documentation]
