= Amazon EventBridge Client

include::./includes/attributes.adoc[]

Amazon EventBridge is a serverless event bus service that makes it easy to connect your applications with data from a variety of sources.

You can find more information about EventBridge at https://docs.aws.amazon.com/eventbridge/latest/APIReference[AWS EventBridge Data Streams Service API Reference].

NOTE: The EventBridge extension is based on https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html[AWS Java SDK 2.x].
It's a major rewrite of the 1.x code base that offers two programming models (Blocking & Async).

The Quarkus extension supports two programming models:

* Blocking access using URL Connection HTTP client (by default) or the Apache HTTP Client
* https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html[Asynchronous programming] based on JDK's `CompletableFuture` objects and the Netty HTTP client.

In this guide, we see how you can get your REST services to use EventBridge locally and on AWS.

== Prerequisites

To complete this guide, you need:

* JDK 17+ installed with `JAVA_HOME` configured appropriately
* an IDE
* Apache Maven {maven-version}
* An AWS Account to access the EventBridge service
* Docker for your system to run EventBridge locally for testing purposes

=== Provision EventBridge locally via Dev Services

The easiest way to start working with EventBridge is to run a local instance using Dev Services.

=== Provision EventBridge locally manually

You can also set up a local version of EventBridge manually, first start a LocalStack container:

[source,bash,subs="verbatim,attributes"]
----
docker run --rm --name local-eventbridge --publish 4592:4592 -e SERVICES=events -e START_WEB=0 -d localstack/localstack:3.7.2
----
This starts a EventBridge instance that is accessible on port `4592`.

Create an AWS profile for your local instance using AWS CLI:
[source,shell,subs="verbatim,attributes"]
----
$ aws configure --profile localstack
AWS Access Key ID [None]: test-key
AWS Secret Access Key [None]: test-secret
Default region name [None]: us-east-1
Default output format [None]:
----
== Creating the Maven project

First, we need a new project. Create a new project with the following command:

[source,bash,subs=attributes+]
----
mvn io.quarkus.platform:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=amazon-eventbridge-quickstart \
    -DclassName="org.acme.eventbridge.QuarkusEventBridgeSyncResource" \
    -Dpath="/sync" \
    -Dextensions="resteasy-reactive-jackson,amazon-eventbridge"
cd amazon-eventbridge-quickstart
----

This command generates a Maven structure importing the RESTEasy Reactive/JAX-RS and Amazon EventBridge Client extensions.
After this, the `amazon-eventbridge` extension has been added to your `pom.xml` as well as the Mutiny support for RESTEasy.

== Configuring EventBridge clients

Both EventBridge clients (sync and async) are configurable via the `application.properties` file that can be provided in the `src/main/resources` directory.
Additionally, you need to add to the classpath a proper implementation of the sync client. By default the extension uses the URL connection HTTP client, so
you need to add a URL connection client dependency to the `pom.xml` file:

[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>url-connection-client</artifactId>
</dependency>
----

If you want to use the Apache HTTP client instead, configure it as follows:
[source,properties]
----
quarkus.eventbridge.sync-client.type=apache
----

And add the following dependency to the application `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>apache-client</artifactId>
</dependency>
----


If you want to use the AWS CRT-based HTTP client instead, configure it as follows:
[source,properties]
----
quarkus.eventbridge.sync-client.type=aws-crt
----

And add the following dependency to the application `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>aws-crt-client</artifactId>
</dependency>
----

If you're going to use a local EventBridge instance, configure it as follows:

[source,properties]
----
quarkus.eventbridge.endpoint-override=http://localhost:4592 <1>

quarkus.eventbridge.aws.region=us-east-1 <2>
quarkus.eventbridge.aws.credentials.type=static <3>
quarkus.eventbridge.aws.credentials.static-provider.access-key-id=test-key
quarkus.eventbridge.aws.credentials.static-provider.secret-access-key=test-secret
----

<1> Override the EventBridge client to use LocalStack instead of the actual AWS service
<2> Localstack defaults to `us-east-1`
<3> The `static` credentials provider lets you set the `access-key-id` and `secret-access-key` directly

If you want to work with an AWS account, you can simply remove or comment out all Amazon EventBridge related properties. By default, the ST client extension will use the `default` credentials provider chain that looks for credentials in this order:

include::./amazon-credentials.adoc[]

And the region from your AWS CLI profile will be used.

== Next steps

=== Packaging

Packaging your application is as simple as `./mvnw clean package`.
It can then be run with `java -Dparameters.path=/quarkus/is/awesome/ -jar target/quarkus-app/quarkus-run.jar`.

With GraalVM installed, you can also create a native executable binary: `./mvnw clean package -Dnative`.
Depending on your system, that will take some time.

=== Going asynchronous

Thanks to the AWS SDK v2.x used by the Quarkus extension, you can use the asynchronous programming model out of the box.

We need to add the Netty HTTP client dependency to the `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>netty-nio-client</artifactId>
</dependency>
----

If you want to use the AWS CRT-based HTTP client instead, configure it as follows:
[source,properties]
----
quarkus.eventbridge.async-client.type=aws-crt
----

And add the following dependency to the application `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>aws-crt-client</artifactId>
</dependency>
----

== Configuration Reference

include::./includes/quarkus-amazon-eventbridge.adoc[]
