= Amazon STS Client

include::./includes/attributes.adoc[]

AWS Security Token Service (AWS STS) is a web service that enables you to request temporary, limited-privilege credentials for users.

You can find more information about STS at https://docs.aws.amazon.com/STS/latest/APIReference[AWS Security Token Service API Reference].

NOTE: The STS extension is based on https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html[AWS Java SDK 2.x].
It's a major rewrite of the 1.x code base that offers two programming models (Blocking & Async).

The Quarkus extension supports two programming models:

* Blocking access using URL Connection HTTP client (by default) or the Apache HTTP Client
* https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html[Asynchronous programming] based on JDK's `CompletableFuture` objects and the Netty HTTP client.

In this guide, we see how you can get your REST services to use STS locally and on AWS.

== Prerequisites

To complete this guide, you need:

* JDK 11+ installed with `JAVA_HOME` configured appropriately
* an IDE
* Apache Maven {maven-version}
* An AWS Account to access the STS service
* Docker for your system to run STS locally for testing purposes

=== Provision STS locally via Dev Services

The easiest way to start working with STS is to run a local instance using Dev Services.

=== Provision STS locally manually

You can also set up a local version of STS manually, first start a LocalStack container:

[source,bash,subs="verbatim,attributes"]
----
docker run --rm --name local-sts --publish 4592:4592 -e SERVICES=sts -e START_WEB=0 -d localstack/localstack:1.0.3
----
This starts a STS instance that is accessible on port `4592`.

Create an AWS profile for your local instance using AWS CLI:
[source,shell,subs="verbatim,attributes"]
----
$ aws configure --profile localstack
AWS Access Key ID [None]: test-key
AWS Secret Access Key [None]: test-secret
Default region name [None]: us-east-1
Default output format [None]:
----
== Creating the Maven project

First, we need a new project. Create a new project with the following command:

[source,bash,subs=attributes+]
----
mvn io.quarkus.platform:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=amazon-sts-quickstart \
    -DclassName="org.acme.sts.QuarkusStsSyncResource" \
    -Dpath="/sync" \
    -Dextensions="resteasy-reactive-jackson,amazon-sts"
cd amazon-sts-quickstart
----

This command generates a Maven structure importing the RESTEasy Reactive/JAX-RS and Amazon STS Client extensions.
After this, the `amazon-sts` extension has been added to your `pom.xml` as well as the Mutiny support for RESTEasy.

== Configuring STS clients

Both STS clients (sync and async) are configurable via the `application.properties` file that can be provided in the `src/main/resources` directory.
Additionally, you need to add to the classpath a proper implementation of the sync client. By default the extension uses the URL connection HTTP client, so
you need to add a URL connection client dependency to the `pom.xml` file:

[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>url-connection-client</artifactId>
</dependency>
----

If you want to use Apache HTTP client instead, configure it as follows:

[source,properties]
----
quarkus.sts.sync-client.type=apache
----

And add the following dependency to the application `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>apache-client</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-apache-httpclient</artifactId>
</dependency>
----

If you're going to use a local STS instance, configure it as follows:

[source,properties]
----
quarkus.sts.endpoint-override=http://localhost:4592 <1>

quarkus.sts.aws.region=us-east-1 <2>
quarkus.sts.aws.credentials.type=static <3>
quarkus.sts.aws.credentials.static-provider.access-key-id=test-key
quarkus.sts.aws.credentials.static-provider.secret-access-key=test-secret
----

<1> Override the STS client to use LocalStack instead of the actual AWS service
<2> Localstack defaults to `us-east-1`
<3> The `static` credentials provider lets you set the `access-key-id` and `secret-access-key` directly

If you want to work with an AWS account, you can simply remove or comment out all Amazon STS related properties. By default, the ST client extension will use the `default` credentials provider chain that looks for credentials in this order:

include::./amazon-credentials.adoc[]

And the region from your AWS CLI profile will be used.

== Next steps

=== Packaging

Packaging your application is as simple as `./mvnw clean package`.
It can then be run with `java -Dparameters.path=/quarkus/is/awesome/ -jar target/quarkus-app/quarkus-run.jar`.

With GraalVM installed, you can also create a native executable binary: `./mvnw clean package -Dnative`.
Depending on your system, that will take some time.

== Configuration Reference

include::./includes/quarkus-amazon-sts.adoc[]
