= Amazon Payment Cryptography Data Client

include::./includes/attributes.adoc[]

Amazon Payment Cryptography simplifies cryptography operations in your cloud-hosted payment applications. You can use Amazon Payment Cryptography Data to use encryption keys for payment-related transaction processing and associated cryptographic operations.

You can find more information about Payment Cryptography at https://aws.amazon.com/payment-cryptography/[the Amazon Payment Cryptography website].

NOTE: The Payment Cryptography Data extension is based on https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html[AWS Java SDK 2.x].
It's a major rewrite of the 1.x code base that offers two programming models (Blocking & Async).

The Quarkus extension supports two programming models:

* Blocking access using URL Connection HTTP client (by default) or the Apache HTTP Client
* https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html[Asynchronous programming] based on JDK's `CompletableFuture` objects and the Netty HTTP client (by default) or the AWS CRT-based HTTP client

include::./includes/quarkus-amazon-paymentcryptographydata.adoc[]
