= Amazon CloudWatch Client

include::./includes/attributes.adoc[]

AWS CloudWatch enables you to publish, monitor, and manage various metrics, as well as configure alarm actions based on data from metrics.

You can find more information about CloudWatch at https://docs.aws.amazon.com/cloudwatch/[the AWS CloudWatch website].

NOTE: The CloudWatch extension is based on https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html[AWS Java SDK 2.x].
It's a major rewrite of the 1.x code base that offers two programming models (Blocking & Async).

The Quarkus extension supports two programming models:

* Blocking access using URL Connection HTTP client (by default) or the Apache HTTP Client
* https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html[Asynchronous programming] based on JDK's `CompletableFuture` objects and the Netty HTTP client (by default) or the AWS CRT-based HTTP client

In this guide, we see how you can get your REST services to use CloudWatch locally and on AWS.

== Prerequisites

To complete this guide, you need:

* JDK 17+ installed with `JAVA_HOME` configured appropriately
* an IDE
* Apache Maven {maven-version}
* An AWS Account to access the CloudWatch service
* Docker for your system to run CloudWatch locally for testing purposes

=== Provision CloudWatch locally via Dev Services

The easiest way to start working with CloudWatch is to run a local instance using Dev Services.

=== Provision CloudWatch Manager locally manually

You can also set up a local version of CloudWatch manually, first start a LocalStack container:

[source,bash,subs="verbatim,attributes"]
----
docker run --rm --name local-cloudwatch --publish 4566:4582 -e SERVICES=cloudwatch -e START_WEB=0 -d localstack/localstack:3.0.1
----
This starts CloudWatch instance that is accessible on port `4566`.

Create an AWS profile for your local instance using AWS CLI:
[source,shell,subs="verbatim,attributes"]
----
$ aws configure --profile localstack
AWS Access Key ID [None]: test-key
AWS Secret Access Key [None]: test-secret
Default region name [None]: us-east-1
Default output format [None]:
----

== Solution
The application built here allows listing the available metrics and push data for a specific metric for the provided credentials.

We recommend that you follow the instructions in the next sections and create the application step by step.
However, you can go right to the completed example.

Clone the Git repository: `git clone {quickstarts-clone-url}`, or download an {quickstarts-archive-url}[archive].

The solution is located in the `amazon-cloudwatch-quickstart` {quickstarts-tree-url}/amazon-cloudwatch-quickstart[directory].

== Creating the Maven project

First, we need a new project. Create a new project with the following command:

[source,bash,subs=attributes+]
----
mvn io.quarkus.platform:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=amazon-cloudwatch-quickstart \
    -DclassName="org.acme.cloudwatch.QuarkusCloudWatchSyncResource" \
    -Dpath="/sync" \
    -Dextensions="resteasy,resteasy-jackson,amazon-cloudwatch,resteasy-mutiny"
cd amazon-cloudwatch-quickstart
----

This command generates a Maven structure importing the RESTEasy/JAX-RS, Mutiny and Amazon CloudWatch Client extensions.
After this, the `amazon-cloudwatch` extension has been added to your `pom.xml` as well as the Mutiny support for RESTEasy.

== Creating JSON REST service

In this example, we will create an application that allows us listing the available metrics and push data for a specific metric with CloudWatch SDK using a RESTful API.
The example application will demonstrate the two programming models supported by the extension.

Let's start with an abstract `org.acme.cloudwatch.QuarkusCloudWatchResource` class to provide the common functionality we will need for both the synchronous and asynchronous exposures.

[source,java]
----
package org.acme.cloudwatch;

import jakarta.enterprise.context.ApplicationScoped;
import software.amazon.awssdk.services.cloudwatch.model.ListMetricsRequest;
import software.amazon.awssdk.services.cloudwatch.model.MetricDatum;
import software.amazon.awssdk.services.cloudwatch.model.PutMetricDataRequest;

import java.time.Instant;

public abstract QuarkusCloudWatchResource {

    protected ListMetricsRequest generateListMetricsRequest(String namespace) {
        return ListMetricsRequest.builder().namespace(namespace).build(); <1>
    }


    protected PutMetricDataRequest generatePutMetricRequest(String namespace, String metricName) {
        return PutMetricDataRequest.builder()
                .namespace(namespace)
                .metricData(MetricDatum.builder()
                        .metricName(metricName)
                        .timestamp(Instant.now())
                        .counts(1.0)
                        .unit("Invocation")
                        .build())
                .build(); <2>
    }


}

----

<1> Generate a request to list all metrics with a specific namespace
<2> Generate a request to put data for a specific metric within a namespace

Now, we can extend the class and create the synchronous implementation in the `org.acme.cloudwatch.QuarkusCloudWatchSyncResource` class.

[source,java]
----
package org.acme.cloudwatch;


import io.quarkus.logging.Log;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import software.amazon.awssdk.services.cloudwatch.CloudWatchClient;
import software.amazon.awssdk.services.cloudwatch.model.Metric;

import java.util.List;

@Path("/sync")
public class QuarkusCloudWatchSyncResource  extends QuarkusCloudWatchResource {
    @Inject <1>
    CloudWatchClient client;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String listMetricsNames(@QueryParam("namespace") String namespace) {

        Log.info("List Metrics for " + namespace);

        List<String> listOfMetrics = client.listMetricsPaginator(generateListMetricsRequest(namespace))
                .stream()
                .flatMap(value -> value.metrics().stream())
                .map(Metric::metricName).toList();

        return String.join(", ", listOfMetrics);
    }

    @PUT
    @Produces(MediaType.TEXT_PLAIN)
    public String createMetric(@FormParam("namespace") String namespace,
                               @FormParam("name") String name) {
        Log.info("Put Metrics for " + namespace + "." + name);
        client.putMetricData(generatePutMetricRequest(namespace, name));
        return "OK";
    }
}
----

<1> Inject the client provided by the amazon-cloudwatch extension

Using the Amazon CloudWatch SDK, we can get & push metric data to CloudWatch.

== Configuring CloudWatch clients

Both CloudWatch clients (sync and async) are configurable via the `application.properties` file that can be provided in the `src/main/resources` directory.
Additionally, you need to add to the classpath a proper implementation of the sync client. By default the extension uses the URL connection HTTP client, so
you need to add a URL connection client dependency to the `pom.xml` file:

[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>url-connection-client</artifactId>
</dependency>
----

If you want to use the Apache HTTP client instead, configure it as follows:
[source,properties]
----
quarkus.cloudwatch.sync-client.type=apache
----

And add the following dependency to the application `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>apache-client</artifactId>
</dependency>
----

If you want to use the AWS CRT-based HTTP client instead, configure it as follows:
[source,properties]
----
quarkus.cloudwatch.sync-client.type=aws-crt
----

And add the following dependency to the application `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>aws-crt-client</artifactId>
</dependency>
----


If you're going to use a local CloudWatch instance, configure it as follows:

[source,properties]
----
quarkus.cloudwatch.endpoint-override=http://localhost:4566 <1>

quarkus.cloudwatch.aws.region=us-east-1 <2>
quarkus.cloudwatch.aws.credentials.type=static <3>
quarkus.cloudwatch.aws.credentials.static-provider.access-key-id=test-key
quarkus.cloudwatch.aws.credentials.static-provider.secret-access-key=test-secret
----

<1> Override the CloudWatch client to use LocalStack instead of the actual AWS service
<2> Localstack defaults to `us-east-1`
<3> The `static` credentials provider lets you set the `access-key-id` and `secret-access-key` directly

If you want to work with an AWS account, you can simply remove or comment out all Amazon CloudWatch related properties. By default, the CloudWatch client extension will use the `default` credentials provider chain that looks for credentials in this order:

include::./amazon-credentials.adoc[]

And the region from your AWS CLI profile will be used.

== Next steps

=== Packaging

Packaging your application is as simple as `./mvnw clean package`.
It can then be run with `java  -jar target/quarkus-app/quarkus-run.jar`.

With GraalVM installed, you can also create a native executable binary: `./mvnw clean package -Dnative`.
Depending on your system, that will take some time.

=== Going asynchronous

Thanks to the AWS SDK v2.x used by the Quarkus extension, you can use the asynchronous programming model out of the box.

Create a `org.acme.cloudwatch.QuarkusCloudWatchAsyncResource` REST resource that will be similar to our `QuarkusCloudWatchSyncResource` but using an asynchronous programming model.

[source,java]
----
package org.acme.cloudwatch;

import io.quarkus.logging.Log;
import io.smallrye.mutiny.Multi;
import io.smallrye.mutiny.Uni;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import software.amazon.awssdk.services.cloudwatch.CloudWatchAsyncClient;
import software.amazon.awssdk.services.cloudwatch.model.Metric;
import software.amazon.awssdk.services.cloudwatch.paginators.ListMetricsPublisher;

@Path("/async")
public class QuarkusCloudWatchAsyncResource extends QuarkusCloudWatchResource {

    @Inject
    CloudWatchAsyncClient client;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Uni<String> listMetricsNames(@QueryParam("namespace") String namespace) {

        return Multi.createFrom().<Metric>emitter((emitter) -> {

                    Log.info("List Metrics for " + namespace);

                    ListMetricsPublisher paginator = client
                            .listMetricsPaginator(generateListMetricsRequest(namespace));

                    paginator.doAfterOnComplete(emitter::complete)
                            .doAfterOnError(emitter::fail)
                            .subscribe(response -> response.metrics().forEach(emitter::emit));


                }).map(Metric::metricName)
                .collect().asList()
                .map(value -> String.join(", ", value));


    }

    @PUT
    @Produces(MediaType.TEXT_PLAIN)
    public Uni<String> createMetric(@FormParam("namespace") String namespace,
                                    @FormParam("name") String name) {

        Log.info("Put Metrics for " + namespace + "." + name);
        return Uni.createFrom().completionStage(
                client.putMetricData(generatePutMetricRequest(namespace, name))
        ).map(value -> "OK");


    }
}
----

Note that the `CloudWatchAsyncClient` behaves just like the `CloudWatchClient`, but returns `CompletionStage` objects which we use to create `Uni`/`Multi` instances, and then transform the emitted item.

To enable the asynchronous client, we also need to add the Netty HTTP client dependency to the `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>netty-nio-client</artifactId>
</dependency>
----

If you want to use the AWS CRT-based HTTP client instead, configure it as follows:
[source,properties]
----
quarkus.cloudwatch.async-client.type=aws-crt
----

And add the following dependency to the application `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>aws-crt-client</artifactId>
</dependency>
----

== Configuration Reference

include::./includes/quarkus-amazon-cloudwatch.adoc[]
