= OpenTelemetry for Amazon Services

Quarkus Amazon Services facilitates integration of the https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/README[AWS SDK instrumentation].

Adding the `quarkus-opentelemetry` extension will automatically inject an interceptor with default AwsSdkTelemetry configuration in all produced extension clients that have opted into instrumentation. This is achieved by setting the configuration property `quarkus.<extension>.telemetry.enabled` to true. This setting is set to `false` by default.

Quarkus Amazon Services supports the OpenTelemetry Autoconfiguration for Traces. The configurations match what you can see at OpenTelemetry SDK Autoconfigure with the `quarkus.*` prefix.

If necessary, you can provide your own AwsSdkTelemetry instance used to instrument all clients.

[source,java]
----
package org.acme;

import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.instrumentation.awssdk.v2_2.AwsSdkTelemetry;
import io.quarkus.arc.Unremovable;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;
import jakarta.inject.Singleton;

@ApplicationScoped
public class MyProducer {

    @Produces
    @Singleton
    @Unremovable
    public AwsSdkTelemetry myTelemetry() {
        return AwsSdkTelemetry.builder(OpenTelemetry.noop()).build();
    }
}
----

== Configuration Reference

include::./includes/quarkus-otel-instrumentation-aws-sdk-telemetry-config.adoc[]
