<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.quarkiverse.amazonservices</groupId>
        <artifactId>quarkus-amazon-services-services-parent</artifactId>
        <version>3.22.1</version>
    </parent>

    <artifactId>quarkus-amazon-ce-parent</artifactId>
    <name>Quarkus - Amazon Services - Relocations - quarkus-amazon-ce-parent</name>
    <packaging>pom</packaging>

    <distributionManagement>
        <relocation>
            <artifactId>quarkus-amazon-costexplorer-parent</artifactId>
            <version>${project.version}</version>
            <message>quarkus-amazon-ce-parent has been relocated to quarkus-amazon-costexplorer-parent. Please update your pom.xml.</message>
        </relocation>
    </distributionManagement>

    <modules>
        <module>runtime</module>
        <module>deployment</module>
    </modules>

</project>
