package io.quarkiverse.it.amazon.dynamodb.enhanced;

import static software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior.WRITE_IF_NOT_EXISTS;

import java.time.Instant;

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

@DynamoDbImmutable(builder = DynamoDBExampleTableEntryImmutable.Builder.class)
public class DynamoDBExampleTableEntryImmutable {

    private String keyId;

    private String rangeId;

    private Long version;

    private Instant createdAtTimestamp;

    private Instant updatedAt;

    private String payload;

    public String getPayload() {
        return payload;
    }

    private DynamoDBExampleTableEntryImmutable(Builder b) {
        this.keyId = b.keyId;
        this.rangeId = b.rangeId;
        this.version = b.version;
        this.payload = b.payload;
        this.createdAtTimestamp = b.createdAtTimestamp;
        this.updatedAt = b.updatedAt;
    }

    @DynamoDbPartitionKey
    public String getKeyId() {
        return keyId;
    }

    public String getRangeId() {
        return rangeId;
    }

    @DynamoDbVersionAttribute
    public Long getVersion() {
        return version;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(value = WRITE_IF_NOT_EXISTS)
    public Instant getCreatedAtTimestamp() {
        return createdAtTimestamp;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private String keyId;
        private String rangeId;
        private Long version;
        private String payload;
        private Instant createdAtTimestamp;
        private Instant updatedAt;

        public Builder keyId(String keyId) {
            this.keyId = keyId;
            return this;
        }

        public Builder rangeId(String rangeId) {
            this.rangeId = rangeId;
            return this;
        }

        public Builder version(Long version) {
            this.version = version;
            return this;
        }

        public Builder payload(String payload) {
            this.payload = payload;
            return this;
        }

        public Builder createdAtTimestamp(Instant createdAtTimestamp) {
            this.createdAtTimestamp = createdAtTimestamp;
            return this;
        }

        public Builder updatedAt(Instant updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public DynamoDBExampleTableEntryImmutable build() {
            return new DynamoDBExampleTableEntryImmutable(this);
        }
    }
}
